export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_ERROR = 'ADD_CUSTOMER_ERROR';
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const LOAD_CUSTOMERS_ERROR = 'LOAD_CUSTOMERS_ERROR';
export const BEGIN_ADD_CUSTOMER = 'BEGIN_ADD_CUSTOMER';
export const BEGIN_LOAD_CUSTOMERS = 'BEGIN_LOAD_CUSTOMERS';