export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const LOAD_CUSTOMERS_ERROR = 'LOAD_CUSTOMERS_ERROR';
export const BEGIN_CREATE_CUSTOMER = 'BEGIN_CREATE_CUSTOMER';
export const BEGIN_LOAD_CUSTOMERS = 'BEGIN_LOAD_CUSTOMERS';